### PR TITLE
Update Point1.py

### PR DESCRIPTION
**Pull request by Kellyb91**

### CODE REVIEW

**Comment by Kellyb91** [comment]
hi 

i am very new to github and I am doing a university course and wanted to play about with this code for learning purposes

**Comment by AllenDowney** [comment]
Sounds good. I hope you're enjoying the book.

Did you open this PR to make a correction or suggest a change?

**Comment by AllenDowney** [comment]
I'll close this for now.

**Comment by Kellyb91** [comment]
No I didn’t sorry! I have no idea how GitHub works at the minute.

Thanks for understanding
Kelly

Sent from my iPhone

On 22 Oct 2024, at 18:29, Allen Downey ***@***.***> wrote:

﻿

I'll close this for now.

**Comment by AllenDowney** [comment]
No problem -- learn by doing!

**Pull request closed without merging**
